version: 2.1

.aliases:
  - &on-release
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /v[0-9]+(\.[0-9]+)*(-.*)*/

orbs:
  terraform: ovotech/terraform@1

jobs:
  go-release:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: goreleaser
          command: |
            echo $DOCKER_PASS | docker login -u=$DOCKER_USER --password-stdin
            curl -sL https://git.io/goreleaser | VERSION=v0.157.0 bash

  go-test:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: make test

  go-lint:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - run: make lint

  go-build:
    docker:
      - image: circleci/golang:1.15
    steps:
      - checkout
      - setup_remote_docker
      - run: make build

  tf-check:
    executor: terraform/terraform-0_12
    steps:
      - checkout
      - terraform/fmt-check:
          path: terraform/gcp

  tf-validate:
    executor: terraform/terraform-0_12
    steps:
      - checkout
      - terraform/validate:
          path: terraform/gcp

  tf-publish:
    executor: terraform/terraform-0_12
    steps:
      - checkout
      - terraform/publish-module:
          path: terraform/gcp
          module_name: pe/bigquery-metrics-exporter/gcp
          version_file_path: terraform/gcp/module_version.txt

workflows:
  release:
    jobs:
      - go-release:
          <<: *on-release
      - tf-publish:
          <<: *on-release

  quality-checks:
    jobs:
      - go-test
      - go-lint
      - go-build
      - tf-check
      - tf-validate
