version: 2.1

.aliases:
  - &on-release
    filters:
      branches:
        ignore: /.*/
      tags:
        only: /v[0-9]+(\.[0-9]+)*(-.*)*/
  - &on-main
    filters:
      branches:
        only: main
  - &on-schedule
    when:
      and:
        - equal: [scheduled_pipeline, << pipeline.trigger_source >>]
        - equal: [nightly_build_workflow, << pipeline.schedule.name >>]
  - &not-on-schedule
    when:
      not:
        equal: [scheduled_pipeline, << pipeline.trigger_source >>]

orbs:
  terraform: ovotech/terraform@1
  sast-terraform: ovotech/sast-terraform@1.0.0
  scheduled-pipeline: ovotech/setup-scheduled-pipeline@1.0.1

jobs:
  go-release:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run:
          name: goreleaser
          command: |
            echo $DOCKER_PASS | docker login -u=$DOCKER_USER --password-stdin
            curl -sL https://git.io/goreleaser | VERSION=v0.157.0 bash

  go-test:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: make test

  go-lint:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - run: make lint

  go-build:
    docker:
      - image: cimg/go:1.18
    steps:
      - checkout
      - setup_remote_docker
      - run: make build

  tf-check:
    executor: terraform/terraform-0_12
    steps:
      - checkout
      - run: echo 'version = "0.12.31"' >> terraform/gcp/.tfswitch.toml
      - terraform/fmt-check:
          path: terraform/gcp

  tf-validate:
    executor: terraform/terraform-0_12
    steps:
      - checkout
      - run: echo 'version = "0.12.31"' >> terraform/gcp/.tfswitch.toml
      - terraform/validate:
          path: terraform/gcp

  tf-publish:
    executor: terraform/terraform-0_12
    steps:
      - checkout
      - terraform/publish-module:
          path: terraform/gcp
          module_name: pe/bigquery-metrics-exporter/gcp
          version_file_path: terraform/gcp/module_version.txt

workflows:
  release:
    <<: *not-on-schedule
    jobs:
      - go-release:
          <<: *on-release
      - tf-publish:
          <<: *on-release

  quality-checks:
    <<: *not-on-schedule
    jobs:
      - go-test
      - go-lint
      - go-build
      - tf-check
      - tf-validate
      - sast-terraform/checkov_static_code_analysis:
          directory: terraform/gcp

  nightly-build:
    <<: *on-schedule
    jobs:
      - go-test
      - go-lint
      - go-build

  define-triggers:
    jobs:
      - scheduled-pipeline/create_scheduled_pipeline:
          <<: *on-main
          schedule_name: nightly_build_workflow
          schedule_description: Workflow for nightly builds
          schedule_hours: 23
          schedule_days: MON,TUE,WED,THU,FRI,SAT,SUN
